global using Microsoft.Extensions.DependencyInjection;
global using DamienVDKHttpClient.Services;
global using System;
global using System.Net.Http;
global using System.Threading.Tasks;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Linq;
global using DamienVDKHttpClient;
global using DamienVDKHttpClient.Extensions;